= Byte code i maszyna wirtualna
:backend: revealjs
:highlighter: pygments
:stem: asciimath
:source-highlighter: pygments
:pygments-css: style
:revealjs_theme: serif
:revealjs_history: true


== Byte code i maszyna wirtualna

  Java Virtual Machine bytecode is a low level language for non existing CPU

=== .class file structure

----
ClassFile {
    u4             magic;
    u2             minor_version;
    u2             major_version;
    u2             constant_pool_count;
    cp_info        constant_pool[constant_pool_count-1];
    u2             access_flags;
    u2             this_class;
    u2             super_class;
    u2             interfaces_count;
    u2             interfaces[interfaces_count];
    u2             fields_count;
    field_info     fields[fields_count];
    u2             methods_count;
    method_info    methods[methods_count];
    u2             attributes_count;
    attribute_info attributes[attributes_count];
}
----

=== Struktura pliku .class

Bytecode is stored in files, which format is defined by
link:http://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html[lass
  file format spec]

Bytecode is a stream of single byte size opcodes followed by
defined set operands

=== Hello world

[source, asm]
----
0: getstatic #16
3: ldc #22
5: invokevirtual #24
8: return
----

=== Constant pool

----
#1 = Utf8               ClassWithDefaultConstructor
#2 = Class              #1             // ClassWithDefaultConstructor
#3 = Utf8               java/lang/Object
#4 = Class              #3             // java/lang/Object
#5 = Utf8               <init>
#6 = Utf8               (Ljava/lang/Integer;)V
#7 = Utf8               ()V
#8 = NameAndType        #5:#7          // "<init>":()V
#9 = Methodref          #4.#8          // java/lang/Object."<init>":()V
#10 = Utf8               java/lang/Integer
#11 = Class              #10            // java/lang/Integer
#12 = Utf8               toString
#13 = Utf8               ()Ljava/lang/String;
#14 = NameAndType        #12:#13        // toString:()Ljava/lang/String;
----

=== Interpretacja bytecode

[shaape]
----
                          +-----------------+
                          |                 |
+---------+           +---+-------------+   |
|         |   bci     |                 |   |
| Thread  |---------->| Method bytecode +---+
|         |           |                 |
|         |           +-----------------+
|         |
|         |           +-----------------+
|         |           |                 |
|         |           |  Frame stack    |
|         |           |                 |
|         |           +-----------------+
|         |
|         |           +-----------------+
|         |           |                 |
|         |           | Local variables |
|         |           |                 |
+---------+           +-----------------+
----

=== Bytecode, stack, variables

=== Podstawowe operacje: manipulacja stosem

* `ALOAD`,`ILOAD`,`DLOAD`,`FLOAD`, umieszcza wybraną zmienną lokalną na stosie,
* `DSTORE`,`ASTORE`,`ISTORE`,`FSTORE`, umieszcza wartość z stosu w tablicy zmiennych lokalnych
* każdy z powyższysz opcode przyjmuje dodatkowy bajt jak indeks w tablicy zmiennych lokalnych
* `DUP`, powiela obiekt na stosie,
* `POP`, usuwa obiekt z stosu

=== invoke*

* Bytecode posiada 5 różnych instrukcji służących do wywoływania metod,
** `invokevirtual`
** `invokespecial`
** `invokeinterface`
** `invokestatic`
** `invokedynamic`


=== invoke* and receiver

** różnią się typem tzw. `receiver` czyli pierwszego elementu na stosie oraz
w jaki sposób jest określania metoda, która ma zostać wywołana

=== virtual, special, interface

* wszystkie powyższe bytecode wymagają by pierwszym elementem na stosie był
tzw. `receiver`, czyli obiekt na którym zostanie wywołana metoda, przy czym
** `invokevirtual`, class of object
** `invokespecial`, type of reference
** `invokeinterface`, same as invoke virtual but reference type must be interface,

=== invokeinterface

* why a separate opcode is necessary for interface references?
* when the Java virtual machine loads a class file, it may create a method table for the class.
* _method table_ is just an array of direct references to the bytecodes for each
instance method that can be invoked on an object, including methods inherited
from superclasses.

=== invokeinterface

* JVM uses a different opcode to invoke a method given an interface reference
because it can't make as many assumptions about the method table offset as it
can given a class reference.

=== invokeinterface

* if the JVM has a class reference, it knows each method will always occupy the
same position in the method table, independent of the actual class of the object.
* this is not true with an interface reference: The method could occupy different
locations for different classes that implement the same interface.
* more about it, http://www.artima.com/underthehood/invocationP.html

=== invokedynamic

* `invokedynamic` means the ability to invoke a method without statically
binding to a specific type, and perhaps additionally without specifying static
types for the parameter list
* `invokedynamic` is linked at runtime by use of _bootstrap_ methods, which
return method handles
* this was original designed to support dynamic languages and is also foundation
of lambdas implementation in JDK 8

=== Exception table

----
0: invokestatic  #16 // Method callSomething:()V
3: goto          36
6: astore_1
7: getstatic     #19 // Field java/lang/System.out:Ljava/io/PrintStream;
36: getstatic     #19 // Field java/lang/System.out:Ljava/io/PrintStream;
39: ldc           #31 // String Done
41: invokevirtual #33 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
44: return
    Exception table:
       from    to  target type
           0     3     6   Class java/lang/Exception
           0    14    25   any
----

=== Exception table

* przechowuje informacje o blokach kodu `catch` oraz `finnaly`, wdanej metodzie
* oraz mapowanie pomiędzy typem wyjątku a blockiem kodu
* bytecode nie posiada opcode dla słów kluczowych `catch` i `finally` (Java)

=== StackMapTable

* atrybut wspierany przez javac i JVM od wersji JDK 6, wymagany od wersji JDK 7,
* jest wykorzystywny podczas weryfikacji kontroli typów poprzez "class loader"
* jest to kolekcja tzw. "stack map frames"
* przyspiesza ładowanie .class oraz gwarantuje mniejsze zużycie pamięci

=== LocalVariableTable

* jest to opcjonalny atrybut, wykorzystywane przez debugger, przechowuje
informacje o nazwach zmiennych

=== LineNumberTable

* jest to opcjonalny atrybut, wykorzystywane przez debugger, przechowuje
mapowanie pomiędzy numerem lini w pliku źródłowym a bci (bytecode index)

=== Specyfikacja bytecode

* link:https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html[The class File Format]
* narzędzia,
** javap, disassembler dostępny w JDK
** org.objectweb.asm.util.ASMifier, z biblioteki ASM
** jarScan od jitwatch

=== Przegląd narzędzi do manipulacji

* ASM
* jitescript
* javassist
* bytebuddy
* byteman

=== Java Instrumentation API

* java.lang.instrument defines mechanism to introspect and transform code before
it is passed to class loader
* class file -> instrument -> class loader

=== coding the agent

[source,java]
----
import java.lang.instrument.ClassFileTransformer;
import java.lang.instrument.Instrumentation;
import java.security.ProtectionDomain;

public class Agent {
	public static void premain(String agentArgs,
							   Instrumentation inst) {
		inst.addTransformer(new ClassFileTransformer() {});
	}
}
----

=== setting up an artifact

[source]
META-INF/MANIFEST.MF
----
Premain-Class: pl.symentis.bytecode.instrument.Agent
----

  java -javaagent:myagent.jar MyClass

=== class definition, redefinition and retransformation

* the request for a new class definition is made with java.lang.ClassLoader#defineClass or its native equivalents.
* the request for a class redefinition is made with Instrumentation.redefineClasses or its native equivalents.

=== class definition, redefinition and retransformation

* the request for a class retransformation is made with Instrumentation#retransformClasses or its native equivalents.
* the transformer is called during the processing of the request, before the class file bytes have been verified or applied.
