= Jeśli wszystko wydaje się pod kontrolą, po prostu nie jedziesz wystarczająco szybko.

Czy zastanawiałeś się kiedyś, co trzeba zrobić, aby Twój kod działał szybciej?
Czy zastanawiałeś się kiedyś, jak zostać „człowiekiem od wydajności”?
Być może zajmujesz się wydajnością, od czasu do czasu, od jednej awarii do kolejnego incydentu o "severity 1"?
I masz w sobie to dziwne uczucie, że robisz to źle?

Być może nigdy nie przejmowałeś się jak szybko działa Twój kod. Od wieków wiadomo jest, że zawsze
jest to problem z bazą danych (lub kogoś innego problem).
A może, po prostu trudno się przyznać, że nie wiesz, jak usprawnić działanie swojego kodu?

Podczas tej prezentacji pokażę, jak zostać programistą świadomym wydajności swojego kodu. W towarzystwie narzędzi
takich jak JMH, JFR i flamegraphs.

Skupimy się nie tylko na narzędziach, ale także na procesie optymalizowania wydajności. Porozmawiamy o tym, jak dobrej jakości, tzw. "clean code", wpływa na wydajność, dlaczego zbiory danych, które wykorzystujemy, są kluczowe, a także kiedy więcej nie znaczy szybciej.

Podczas całej prezentacji będziemy refaktoryzować i ulepszać jeden, nie tak trywialny przykładu. Coś, co wszyscy z nas znają, lubią i wiedzą jak zaimplementować.

"Benchmark, profil, refaktor, repeat"