= If everything seems under control, you're just not going fast enough.

Have you ever wondered what it takes to make your software run faster?
Have you ever wondered what it takes to become a "performance engineer"?
Or you are doing so-called "adhoc" performance tuning, living your life from
one outage to another severity 1 incident? And you have this strange feeling, that this is
not like things should be?

You have never cared about how your code performances. You knew it was always
problem with database (or somebody else's problem, blaming others is easy).
It is just hard to admit that you don't know how to make your code run faster.

Let me be your guide on this trip. I will show you how to, accompanied by tools
like JMH, JFR and flamegraphs, make your code run faster. We will not only focus on tooling but also on the performance tuning process. We are going to talk about times when benchmarks lie,
why data sets are crucial and when more doesn't mean faster.

During the whole presentation, we will be refactoring and improving the
performance of one, not so trivial code example. Something that everybody knows and something that is fun to implement on your own.

Benchmark, profile, refactor, repeat.


