image: maven:3.6.0-jdk-11-slim

pipelines:
  branches:
    chapter*:
      - step:
          caches:
            - maven
          script: # Modify the commands below to build your repository.
            - mvn -B verify -DforkCount=0 # -B batch mode makes Maven less verbose
    homework*:
      - step:
          caches:
            - maven
          script:
            - mvn -B test-compile
