image: eclipse-temurin:11

pipelines:
  default:
    - step:
        caches:
          - gradle
        script: # Modify the commands below to build your repository.
          - ./gradlew buildModules # -B batch mode makes Maven less verbose
