---
- hosts: all
  user: ubuntu
  strategy: free
  roles:
    - role: Comcast.sdkman
      sdkman_user: ubuntu
      sdkman_group: ubuntu
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 11.0.13-tem }
      sdkman_offline_mode: false
  tasks:
  - name: install packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      - sysdig
      - linux-tools-common
      - linux-tools-generic
      - gdb
      - sysstat
      - lsof
      - procps
      - unzip
      # SDKMAN needs it
      - zip
      # we need it to install flamegraphs
      - git
      - ca-certificates
      - perl-modules
    become: yes
  - name: install virtualbox extensions
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      # we need to mount and access shared folders
      - virtualbox-guest-utils
      - virtualbox-guest-dkms
    become: yes
    tags:
      - vbox
  - name: setup user
    user:
      name: ubuntu
      append: yes
      groups:
        # we need to mount and access shared folders
        - vboxsf
    become: yes
    tags:
      - vbox
  - name: set perf_event_paranoid parameter
    sysctl:
      name: kernel.perf_event_paranoid
      value: "1"
      reload: yes
      state: present
    become: yes
  - name: set kptr_restrict parameter
    sysctl:
      name: kernel.kptr_restrict
      value: "0"
      reload: yes
      state: present
    become: yes
  # - name: JDK home
  #   shell: "sdk home java 11.0.13-tem" 
  #   register: jdk_home
  #   become: yes
  #   become_user: ubuntu
  #   become_flags: -i
  - name: create async profiler directory
    file:
      path: "/home/ubuntu/tools/async-profiler"
      state: directory
  - name: install async profiler
    unarchive:
      src: https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.5/async-profiler-2.5-linux-x64.tar.gz
      dest: "/home/ubuntu/tools/async-profiler"
      remote_src: yes
      creates: "/home/ubuntu/tools/async-profiler/profiler.sh"
  - name: install hsdis
    copy:
        src: hsdis-amd64.so
        dest: "/home/ubuntu/.sdkman/candidates/java/11.0.13-tem/lib/server/hsdis-amd64.so"
        mode: "u=rx"
