= Just in time compiler
:idprefix:
:backend: revealjs
:highlighter: pygments
:stem: asciimath
:source-highlighter: pygments
:pygments-css: style
:revealjs_theme: serif
:revealjs_history: true
:imagesdir: images

== bytecode interpreters

* C++ template
* ASM template
* interpreter frame
* OpenJDK Zero and Shark

== just in time compiler

Jest częscią maszyny wirtualnej HotSpot i jest odpowiedzialny za optymalizację
i kompilację bytecode w czasie działania maszyny wirtualnej.

Historycznie w Sun/OpenJDK/Oracle JDK były od początku dostępna dwa kompilatory,
client (znany także jako C1) oraz server (znany także jako C2 lub opto).

Od wersji JDK8, domyślnie działają one razem jako tzw. tiered compiler,
kontrolowany przez flagę `-XX:+TieredCompilation`

=== Kompilator C1

Jest to szybki kompilator, operujący na https://en.wikipedia.org/wiki/Control_flow_graph[CFG (control flow graph)]
https://en.wikipedia.org/wiki/Static_single_assignment_form[SSA (static single assigement form)] https://en.wikipedia.org/wiki/Intermediate_language#Intermediate_representation[IR (intermediate representation)]

=== Static single assignment

stem:[x=1] +
stem:[y=2] +
stem:[x_1=y] +
stem:[y_1=x_1]

=== Kompilator C1

Kompilator ten wykorzystuje mechanizm szablonów generujących kod natywny a
także liniową alokację rejestrów.

Kompilator C1 odpowiedzialny jest za takie optymalizacje jak, inlining,
constant propagation, value range propagation,
sparse conditional constant propagation, dead code elimination,
global value numbering, partial redundancy elimination, strength reduction,
register allocation.

=== inlining

[source,java]
----
int doubleAndAdd(int x, int y){
  return doubleInt(x)+doubleInt(y);
}

int doubleInt(int i){
  return i+i;
}
----

[source,java]
----
int doubleAndAdd(int x, int y){
  return (x+x)+(y+y);
}
----

=== inlining: matka wszystkich optymalizacji

[source,java]
----
public void m(){
	n(this);
}

public static n(Object obj){
	if(obj==null){
		doSomething();
	}
}
----

=== inlining

[source,java]
----
public void m(){
	if(this==null){
		doSomething();
	}
}
----

=== null check folding

[source,java]
----
public void m(){
	if(false){
		doSomething();
	}
}
----

=== dead code elimination

[source,java]
----
public void m(){
}
----

=== and last but not least

`-XX:+UseFastEmptyMethods`


=== Ekonomia inlining

* nie ma potrzeby tworzenia nowej ramki na stosie (stack frame)
* zbędne staje się odwołanie do tablicy metod wirtualnych (vtable)

=== Ekonomia inlining

* metody które poddają się tej optymalizacji
** `private`
** `final`
** `static`
** pozostałe, w określonych warunkach (ale o tym poźniej)

=== Optymalizacja inlining

* `-XX:FreqInlineSize=325`, maksymalny rozmiar metody (w bytecode), inline przez
C2
* `-XX:InlineSmallCode=2000`
* `-XX:MaxInlineLevel=9`
* `-XX:MaxInlineSize=35`
* `-XX:MaxRecursiveInlizeLevel=1`
* `-XX:MinInliningThreshold=250`

=== Logowanie optymalizacji

`-XX:+UnlockDiagnosticVMOptions -XX:+PrintCompilation -XX:+PrintInlining`

gdy chcesz zapisać wynik kompilacji do pliku
`-XX:+LogCompilation -XX:LogFile=compilation.log`

=== Logowanie optymalizacji
----
15684 3907       4       org.objectweb.asm.ClassReader::<init> (10 bytes)
                !              @ 3   org.objectweb.asm.ClassReader::a (163 bytes)   already compiled into a big method
                               @ 6   org.objectweb.asm.ClassReader::<init> (9 bytes)   inline (hot)
                                 @ 5   org.objectweb.asm.ClassReader::<init> (257 bytes)   inline (hot)
                                   @ 1   java.lang.Object::<init> (1 bytes)   inline (hot)
                                   @ 14   org.objectweb.asm.ClassReader::readShort (27 bytes)   inline (hot)
                                   @ 36   org.objectweb.asm.ClassReader::readUnsignedShort (26 bytes)   inline (hot)
                                   @ 202   org.objectweb.asm.ClassReader::readUnsignedShort (26 bytes)   inline (hot)
                               @ 10   java.util.zip.ZipEntry::isDirectory (10 bytes)   inline (hot)
                                 @ 6   java.lang.String::endsWith (17 bytes)   inline (hot)
                                   @ 13   java.lang.String::startsWith (72 bytes)   inline (hot)
                               @ 18   java.util.zip.ZipEntry::getName (5 bytes)   accessor
                               @ 26   org.eclipse.jetty.annotations.AnnotationParser::isValidClassFileName (145 bytes)   inline (hot)
----

=== Czytanie logów kompilatora

* compilation id
* symbol
* compiler tier (aka level) [1..4], gdzie 1-3 to C1 a 4 to C2
* method
* compiler cause

=== Poziomy kompilacji

* 1 - C1 kompilator, nie uwzględnia danych z pomiarów, małe metody, "accessor"
* 2 - C1 kompilator, po wstępnym profilowaniu, domyślnie 1000 wywołań, dla tiered compilation 1500, wybrane optymalizacje
* 3 - C1 kompilator, pozostałe optymalizacje
* 4 - C2 kompilator

=== Symbole

|===
| Symbol | Meaning

| % | On stack replacement

| s | Synchronized method

| ! | Method has exception handlers

| b | Blocking compilation

| n | Native wrapper

|===

=== Global value numbering

Jest to optymalizacja która pomaga wyeliminować zbędny kod. Odbywa się to
poprzez przypisanie tej samej wartości do zmiennych i wyrażeń, które są tożsame.

[source,java]
----
w := 3      # -> 1
x := 3      # -> 1
y := x + 4  # -> 2
z := w + 4  # -> 2
----

Po zastąpieniu wyrażen które zostały przypisane do tych samych wartości:

[source, java]
----
w := 3
x := w
y := w + 4
z := y
----

=== Kompilator C2

* najbardziej zaawansowany i wydajny kompilator,
* optymalizuje tzw. hot spots
** `InlineFrequencyCount`
** `InlineFrequencyRatio`
** `InlineThrowCount`
** `InlineThrowMaxSize`
** `MaxInlineSize`

[NOTE.speaker]
----
opisy opcji
----

=== sea of nodes

* link:http://http://grothoff.org/christian/teaching/2007/3353/papers/click95simple.pdf['sea of nodes'] jest to forma reprezentacji kodu w postaci DFG (data flow graph)
* wykorzystywana przez C2 kompilator
* opcodes jako węzły, z uporządowanymi wejściami (ordered inputs)

=== sea of nodes: example

[source,java]
----
c = a + b
e = c / d
----

[graphviz]
----
digraph {
  a -> ADD
  b -> ADD
  ADD -> c
  c -> DIV
  d -> DIV
  DIV -> e
}
----

=== register allocation by graph coloring

* cichy bohater HotSpot, wszyscy dyskutują inlinining, jednak ten mechanizm
zapewniam
** optymalne wykorzystanie rejestrów procesora
** zmniejszenie odwołań do pamięci RAM
* wykorzystywany algorytm to https://en.wikipedia.org/wiki/Graph_coloring[graph coloring]

=== On Stack Replacement

* on stack replacement (OSR) to technika która umożliwia podmianę kodu,
nie tylko po wyjściu z metody
* umożliwia optymalizację długich pętli w ich trakcie działania,
* podmiana kodu odbywa się na tzw. back trace/egde, czyli przy przejsciu pętli
do następnej iteracji

[NOTE.speaker]
----
wyjaśnić back trace
----


=== loop unrolling

* optymalizacja, która zamienia pętle, na wiele powtórzeń tego samego bloku kodu,
**  `-XX:LoopMaxUnroll` = 16
**  `-XX:LoopOptsCount` = 43
**  `-XX:LoopUnrollLimit` = 60
**  `-XX:LoopUnrollMin` = 4
**  `-XX:LoopUnswitching` = true

=== pointer compare

* if JIT compiler can see that a is new object (due to
inlining and escape analisys) it can not be equal
to any previously allocated objects, this triggers pointer compare check folding

=== string concat

* collapses recursive patterns
* pre-allocation of buffer size (counts size of destination string and allocates spaces for it not-zeroing memory)

=== Traps, Type profile and Megamorphs

* 'uncommon traps' aka 'guards' wyzwalają deoptymalizację, ponieważ C2 optymalizuje kod dla najczęstrzych przypadków
* to bloki kodu generowane przez kompilator, sprawdzające poprawność warunków
optymalizacji
* typed profile, przechowuje informacje o oczekiwanym typie tzw. "receiver",

=== lock elision

[source,java]
----
public void getNames(){}
  List v = new Vector(); // <1>
  v.add("Moe"); // <2>
  v.add("Larry");
  v.add("Curly");
  return v;
 }
----
<1> notice use of vector, it is synchronized, but this object never escapes the thread
<2> will inline `add(Object)` method, and remove locks (thanks to escape analisis)

=== biased locking

[source,java]
----
int i = 0;
synchronized(this){

} // <1>
i++;
synchronized(this){

}
----
<1> will not unlock, other thread may need to revoke it, before he will be able
to enter this block

=== biased locking

* `-XX:BiasedLockingStartupDelay=4000`, biased locking is not on, until this delay
* `-XX:BiasedLockingBulkRebiasThreshold=20`,
* `BiasedLockingBulkRevokeThreshold=40`
* `BiasedLockingDecayTime`
* `PrintPreciseBiasedLockingStatistics`
* `TraceBiasedLocking`

=== adaptive locking

* a first attempt to lock is done using a simple compare-and-exchange (CAS)
operation. This is very efficient as it can usually translate into a direct CPU
instruction (e.g cmpxchg).
* if the lock is either free or has been previously biased toward this thread
the lock on the object is obtained for the thread and execution can continue immediately.

=== adaptive locking

* if the CAS fails the JVM will perform one round of spin locking where the
thread parks to effectively put it to sleep between retrying the CAS.
* if these initial attempts fail (signaling a fairly higher level of contention for the lock)
the thread will move itself to a blocked state and enqueue itself in the list of
threads waiting for the lock to be notified

=== adaptive locking: links

* link:http://blog.takipi.com/5-things-you-didnt-know-about-synchronization-in-java-and-scala/[5 Things You Didn’t Know About Synchronization in Java and Scala]
* link:http://arturmkrtchyan.com/jvm-lock-spinning[JVM lock spinning]
* link:http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/share/vm/runtime/synchronizer.cpp[OpenJDK 8 synchronizer]

=== escape analisys (a father of all optimizations)

* it analyzes scope of object's uses, to find out if object is used globally or
is local to a thread
* helps decide whether to allocate it on the Java heap
* enables many other optimizations, like lock elision
* it is available since JDK 6u23, and it is always on
* based on link:http://www-plan.cs.colorado.edu/diwan/7135/escapeOopsla99.ps[Flow-insensitive escape analysis algorithm]

=== Deopitmization

[shaape]
----

+--------------+                       +-----------+
|   Interpret  |---------------------->|  Profile  |
+--------------+                       +-----------+
       ^                                     |
       |                                     |
       |                                     |
       |                                     |
       |                                     |
+--------------+                       +-----------+
|  Deoptimize  |<----------------------|  Compile  |
+--------------+                       +-----------+
----

=== when code gets deoptimized

* triggered by traps (remember C2 optimizes only for most common cases,
  that's why it is called speculative)
* through CHA (class hierarchy analisys), aka type profile
* when code is no longer hot
* more about it at link:http://www.slideshare.net/dougqh/jvm-mechanics-when-does-the[JVM Mechanics: When Does the JVM JIT & Deoptimize?]

=== an example of uncommon case

[source, java]
----
static final int CHUNK_SIZE=1000;

public static void main(String[] argv){
  Object trap = null;
  for(int i=0;i<250;++i){
    for(int j=0;j<CHUNK_SIZE;++j){
      new Object();
      if(trap!=null){ //
        System.out.println("I am being trapped!");
        trap=null;
      }
    }
    if (i == 200){ // <1>
      trap = new Object();
    }
  }
}
----
<1> uncommon trap

=== an example of uncommon case
----
 64   16 %   3     UncommonTrap::main @ 13 (70 bytes)
 65   17     3     UncommonTrap::main (70 bytes)
 65   18 %   4     UncommonTrap::main @ 13 (70 bytes)
I am being trapped!
 67   16 %   3     UncommonTrap::main @ -2 (70 bytes)   made not entrant
----

== Tools

=== disasembly plugin

* this is an unofficial plugin to JVM which prints out assembly code generated
by JIT compilers
* it is required by couple of diagnostic options, more about it at
link:https://wiki.openjdk.java.net/display/HotSpot/PrintAssembly[OpenJDK Wiki]

=== disasembly plugin

* it is not distributed with official JDK, and you have to build it from OpenJDK,
* or download link:https://kenai.com/projects/base-hsdis/downloads[prebuilt binaries]
* you can find it in `hotspot/src/share/tools/hsdis` directory of Open JDK
* once you get binary, you will have to put it in `jre/lib/amd64` directory

=== jitwatch: visualiser for HotSpot

* link:https://github.com/AdoptOpenJDK/jitwatch[jitwatch]
* requires following options `-XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading
-XX:+LogCompilation -XX:LogFile=mylogfile.log`
* if you want to HotSpot to output the disassembled native code then add the JVM switch `-XX:+PrintAssembly`

=== danger ahead: whitebox api

* available since JDK8, it is internal API which let's you manipulate JVM behaviour
* http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/0e4094950cd3/test/testlibrary/whitebox/sun/hotspot/WhiteBox.java[hotspot/test/testlibrary/whitebox/sun/hotspot/WhiteBox.java]
* you can trigger verious events, like GC, JIT compilation
* it used internally for testing

=== building whitebox

[source,bash]
----
cd hotspot/test/testlibrary/whitebox
javac -sourcepath . -d . sun\hotspot\**.java
jar cf wb.jar .
# now you can run your app with it
java -Xbootclasspath/a:wb.jar -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI ...
----

=== using whitebox

[source,java]
----
import sun.hotspot.WhiteBox;

public static class GCYoungTest {
  static WhiteBox wb = WhiteBox.getWhiteBox();
  public static Object obj;

  public static void main(String args[]) {
    obj = new Object();
    System.out.println(wb.isObjectInOldGen(obj));
    wb.youngGC();
    wb.youngGC();
    // 2 young GC is needed to promote object into OldGen
    System.out.println(wb.isObjectInOldGen(obj));
  }
}
----

for this example you need to add `-XX:MaxTenuringThreshold=1` to make it work as expected.

=== Other tools

* http://openjdk.java.net/projects/code-tools/jmh/[Java Microbenchmark Harness]
* http://openjdk.java.net/projects/code-tools/jol/[Java Object Layout]
* and other tools from http://openjdk.java.net/projects/code-tools/[Code tools project]
* profilers, JProfiler, YourKit,

=== Profilers are bad for ya!
